name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - name: Run tests
        shell: nix develop -c bash -e {0}
        run: just test

      - name: Build examples
        shell: nix develop -c bash -e {0}
        run: just build-all

